### ISSUE TITLE
Pad size grows on new pad.

### ISSUE THREAD

**Issue by rimanz** [rimanz/etch-a-sketch#1]
When a new pad is created by clicking the `New` button, the newly created pad is always noticeably bigger than the previous one. For consistency a pad with the exact same height and width should be created.

**Comment by ketansahugit** [comment]
Hi, I think you should close this issue as i just checked. Nothing seems wrong. you probably already fixed it.

**Comment by rimanz** [comment]
@ketansahugit, thank you for informing me.
